kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: react-web-app
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - react-web-app
        from:
          kind: ImageStreamTag
          name: 'react-web-app:latest'
        lastTriggeredImage: >-
          image-registry.openshift-image-registry.svc:5000/hello-world/react-web-app@sha256:8711324008a22eb1a9a0c3d5e89f9f1bd1bf16c185ccc42cd3ef47fdcb6f5c62
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    app: react-web-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: react-web-app
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: react-web-app
          image: >-
            image-registry.openshift-image-registry.svc:5000/hello-world/react-web-app@sha256:8711324008a22eb1a9a0c3d5e89f9f1bd1bf16c185ccc42cd3ef47fdcb6f5c62
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            limits:
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
